### ISSUE TITLE
Released version does not support EventTime ext Type

### ISSUE THREAD

**Issue by cosmo0920** [okumin/influent#16]
I've noticed that released 0.2.0 version does not support msgpack ext type which handles `EventTime`.
This extension type is frequently used in Fluentd v0.14 when not specifying `time-as-interger`.

**Comment by okumin** [comment]
@cosmo0920 OK, I will release the next version this week end.
Wait a few days.
Thanks.

**Comment by okumin** [comment]
@cosmo0920 I published 0.3.0 which support EventTime.
https://github.com/okumin/influent/releases/tag/v0.3.0

Thanks.
